name: Deploy Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  push:
    tags:        
      - v*
    branches:        
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/rv32imc.dockerfile
          tags: bouncmpe/rv32imc
          cache-from: type=registry,ref=bouncmpe/rv32imc:latest
          cache-to: type=registry,ref=bouncmpe/rv32imc:latest,mode=max

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/whisper.dockerfile
          tags: bouncmpe/whisper
          cache-from: type=registry,ref=bouncmpe/whisper:latest
          cache-to: type=registry,ref=bouncmpe/whisper:latest,mode=max

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: bouncmpe/labs344
          push: true
          cache-from: type=registry,ref=bouncmpe/labs344:latest
          cache-to: type=registry,ref=bouncmpe/labs344:latest,mode=max